trigger: none

pr:
  branches:
    include:
      - '*'

variables:
  - group: sonar-project-keys
  - name: projectKey
    value: $(PROJECT_KEY_SD.Plugins-opencart-plugin)

resources:
  repositories:
    - repository: templates
      type: git
      name: SD.Plugins        # Azure DevOps repo where template lives

stages:
- stage: Sonar
  displayName: "SonarQube Scan"
  jobs:
    - template: templates/sonar-flexible-scan.yaml@templates
      parameters:
        projectKey: $(projectKey)
