trigger: none

pr:
  branches:
    include:
      - '*'

variables:
  - group: sonar-project-keys

resources:
  repositories:
    - repository: templates
      type: git
      name: SD.Plugins        # Azure DevOps repo where template lives

stages:
- stage: Sonar
  displayName: "SonarQube Scan"
  jobs:
    - template: templates/sonar-flexible-scan.yaml@templates
